# Generated by Django 3.0.5 on 2020-04-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100, verbose_name='')),
                ('place_description', models.CharField(max_length=250, verbose_name='')),
                ('place_latitude', models.FloatField(verbose_name=0.0)),
                ('place_longitude', models.FloatField(verbose_name=0.0)),
                ('place_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
