# Generated by Django 3.0.5 on 2020-04-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100, verbose_name='Place Name')),
                ('place_categories', models.CharField(choices=[('covid19', 'COVID-19: โรงทานน้ำใจ'), ('rescue', 'Rescue'), ('er-hospital', 'ER-Hospital'), ('aed', 'AED')], max_length=11, verbose_name='Place Categories')),
                ('place_description', models.TextField(blank=True, max_length=2000, verbose_name='Place Description')),
                ('place_enable', models.BooleanField(default=True, verbose_name='Is Place Enable?')),
                ('place_latitude', models.CharField(max_length=50, verbose_name='Place Latitude')),
                ('place_longitude', models.CharField(max_length=50, verbose_name='Place Longitude')),
                ('place_image', models.ImageField(blank=True, upload_to='', verbose_name='Place Image')),
            ],
        ),
    ]
