# Generated by Django 3.0.5 on 2020-04-10 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='place_image',
        ),
        migrations.AlterField(
            model_name='map',
            name='place_categories',
            field=models.CharField(choices=[('covid19', 'COVID-19: โรงทานน้ำใจ'), ('rescue', 'Rescue'), ('erhospital', 'ER-Hospital'), ('aed', 'AED')], max_length=11, verbose_name='Place Categories'),
        ),
        migrations.CreateModel(
            name='Map_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_image', models.ImageField(blank=True, upload_to='', verbose_name='Place Image')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mapapp.Map')),
            ],
        ),
    ]
