# Generated by Django 3.0.5 on 2020-04-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='place_description',
            field=models.CharField(max_length=250, verbose_name='Place Description'),
        ),
        migrations.AlterField(
            model_name='map',
            name='place_latitude',
            field=models.CharField(max_length=50, verbose_name='Place Latitude'),
        ),
        migrations.AlterField(
            model_name='map',
            name='place_longitude',
            field=models.CharField(max_length=50, verbose_name='Place Longitude'),
        ),
        migrations.AlterField(
            model_name='map',
            name='place_name',
            field=models.CharField(max_length=100, verbose_name='Place Name'),
        ),
    ]
