# Generated by Django 3.0.5 on 2020-04-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0002_auto_20200404_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='place_description',
            field=models.TextField(blank=True, max_length=400, verbose_name='Place Description'),
        ),
        migrations.AlterField(
            model_name='map',
            name='place_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='map',
            name='place_latitude',
            field=models.FloatField(max_length=50, verbose_name='Place Latitude'),
        ),
        migrations.AlterField(
            model_name='map',
            name='place_longitude',
            field=models.FloatField(max_length=50, verbose_name='Place Longitude'),
        ),
    ]
