# Generated by Django 3.0.5 on 2020-04-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0003_auto_20200407_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='place_description',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Place Description'),
        ),
    ]
