# Generated by Django 3.0.5 on 2020-04-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0004_auto_20200407_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='place_categories',
            field=models.CharField(blank=True, choices=[('covid19', 'COVID-19: โรงทานน้ำใจ'), ('rescue', 'Rescue'), ('er-hospital', 'ER-Hospital'), ('aed', 'AED')], max_length=11),
        ),
        migrations.AddField(
            model_name='map',
            name='place_enable',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
