# Generated by Django 3.0.5 on 2020-04-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0005_auto_20200407_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='place_categories',
            field=models.CharField(choices=[('covid19', 'COVID-19: โรงทานน้ำใจ'), ('rescue', 'Rescue'), ('er-hospital', 'ER-Hospital'), ('aed', 'AED')], max_length=11, verbose_name='Place Categories'),
        ),
        migrations.AlterField(
            model_name='map',
            name='place_enable',
            field=models.BooleanField(default=True, verbose_name='Is Place Enable?'),
        ),
        migrations.AlterField(
            model_name='map',
            name='place_image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Place Image'),
        ),
    ]
